[pytest]
testpaths = tests
pythonpath = .
addopts =
    -p no:cacheprovider -p no:randomly -p no:xdist
    --cov=app.application.policy
    --cov=app.application.tools
    --cov=app.application.presentation
    --cov-report=term-missing
    --cov-fail-under=90
